### ISSUE TITLE
Why the accuracy of ZeroQ is much higher than the result reported in GDFQ？

### ISSUE THREAD

**Issue by ThisisBillhe** [zysxmu/IntraQ#1]
Hello! 
I was wondering why the result of ZeroQ you reported in the Table.1 of your paper (W4A4, 60.68%on ImageNet) is so high? It's even higher than GDFQ. I clone  ZeroQ's code and the result is similar to GDFQ's paper(~26%). Besides, since ZeroQ's synthetic data don't have its label(without IL), how do you perform fine-tuning on 4-bit ResNet18(caption of Table.1)?
Looking forward to your reply! Thx!

**Comment by zysxmu** [comment]
Hi, the results of GDFQ are directly copied from the original GDFQ paper.

ZeroQ and ZerQ+IL (by adding inception loss) are used to generate fake data. 
Then, we use these generated fake data to fine-tune the quantized model. 
While the original ZeroQ paper only uses fake data to calibrate the quantized model (not fine-tuning).

For ZeroQ, we only use KD loss (minimize the difference between outputs of full-precision model and outputs of the quantized model)
For ZeroQ+IL, we use KD loss and CE loss.
