### ISSUE TITLE
How to reproduce the 3w3a 77.07% on CIFAR-10 ? Why  S loss is nan??

### ISSUE THREAD

**Issue by WhereKey** [zysxmu/IntraQ#3]
In my experiments, I can only get 72.70% on 3w3a CIFAR-10, which is far from the result reported in the paper

**Comment by zysxmu** [comment]
Hi, please make sure the pytorch version is the same at first.
And, you can try 4w4a to determine if you run the right code.

**Comment by zysxmu** [comment]
Moreover, the loss of S is shouldn't be nan.

**Comment by WhereKey** [comment]
> Moreover, the loss of S is shouldn't be nan.

Actually, the train_test.log you provided shows  that the loss of S is nan.  (see cifar10-r20-w4a4/w5a5, cifar100-r20-w4a4/w5a5)

**Comment by zysxmu** [comment]
Oh, sorry for my mistake. This reminds me that the performance on Cifar10 is somehow unstable. 
So, you can run this serval times for better results. Or you can try the ImageNet dataset which is more stable than Cifar10.

**Comment by WhereKey** [comment]
> Oh, sorry for my mistake. This reminds me that the performance on Cifar10 is somehow unstable. So, you can run this serval times for better results. Or you can try the ImageNet dataset which is more stable than Cifar10.

THANKS!
