### ISSUE TITLE
Comparison with previous data-free quantization methods

### ISSUE THREAD

**Issue by DCNSW** [zysxmu/IntraQ#4]
Thanks for your good work on data-free quantization and the release of the code.

[Zero-shot adversarial quantization](https://openaccess.thecvf.com/content/CVPR2021/papers/Liu_Zero-Shot_Adversarial_Quantization_CVPR_2021_paper.pdf)(ZAQ) is also a data-free quantization method with adversarial exploration. I notice that both [IntraQ](https://github.com/zysxmu/IntraQ) and [AIT](https://github.com/iamkanghyunchoi/ait) are not compared to the ZAQ method. Are they solving different problems or having different experiment settings?

Thanks for your tips.

**Comment by zysxmu** [comment]
Thank you for being interested in our work!

ZAQ, IntraQ, AIT are the same type of method that solves the same problems.

But ZAQ employs a generator to produce fake images. In contrast, our method does not use this. Thus, we didn't compare it with our method.

Moreover, in our experiments, we can't reproduce the results as reported in the paper of ZAQ.

**Comment by DCNSW** [comment]
Thanks for your reply.  @zysxmu 

The results of ZAQ you reproduced are on the imagenet dataset or the cifar dataset?
As I see, the [code](https://github.com/FLHonker/ZAQ-code) of ZAQ does not support the imagenet dataset now. Maybe the results (such as 70.06% W4A4 resnet50) on imagenet are reliable, which means the adversarial exploration strategy is suitable for imagenet to tackle data-free quantization problem.

By the way, the issue tab of ZAQ is unavailable.

**Comment by zysxmu** [comment]
Hi, Do you actually reproduce the ZAQ? 
In fact, the code of ZAQ has been modified many times. You can't find the first version now. 
We use the first version once long ago and the results of ImageNet are unreproducible.
If you have any experience, please let me know. Thank you very much. @DCNSW
