### ISSUE TITLE
Results in paper with DSG method

### ISSUE THREAD

**Issue by jiawei-liu1103** [zysxmu/IntraQ#5]
Hi, thanks for your work!
I was wondering why the result of DSG in the Table.3 of your paper is lower than ZeroQ? Since in their paper they claim that DSG performs better than ZeroQ. As far as I know, there was no official open-source code for DSG, but I noticed in your paper (Section 4.1) that you used open-source code. So, did you reproduce DSG personally or had I misunderstood something? Maybe there's something wrong with DSG?

Thanks for your reply

**Comment by zysxmu** [comment]
We reproduce DSG by using the open-source code of ZeroQ.
