### ISSUE TITLE
Question about GAN in training process.

### ISSUE THREAD

**Issue by Minato-Zackie** [zysxmu/IntraQ#8]
Thanks for your work！I notice that in network fine-tuning stage，you used a GAN network to generate data and used the data to train. But this was not mentioned in the paper. If you have time to explain the reason, I'd be very grateful.

**Comment by zysxmu** [comment]
Sorry for late reply.

We follow the setting of GDFQ to initialize our network for a fair comparison. The GAN is only used to initialize the quantized model and not used in the following optimization process.
