### ISSUE TITLE
Confusion about step_S settings

### ISSUE THREAD

**Issue by sscckk** [zysxmu/IntraQ#9]
Thanks for your work!
You mentioned in the paper that "Both learning rates are decayed by 0.1 every 100 fine-tuning epochs." But I noticed that in the code, you set the LR tuning strategy to [20,40,60] for CIFAR10. Looking forward to some explanation from you on this.
Thank you again.

**Comment by zysxmu** [comment]
Sorry for the late reply. The default settings in our GitHub are wrong. Please uses nEpochs = 400 and step_S = [100, 200, 300].
